import Head from "next/head";
import Image from "next/image";
import { About, Feature, Header, Reviews, Screenshots } from "../components";
import Contact from "../components/Contact";
import Footer from "../components/Footer";
import Hero from "../components/Hero";
import styles from "../styles/Home.module.css";

import getAbout, {
  getPosts,
  getrecentPosts,
  getScreenshot,
  getComments,
  getLinks,
  getHero,
} from "../servicees";
import { useLayoutEffect, useState } from "react";
import Loader from "../components/Loader";
import { useEffect } from "react";

export default function Home({
  posts,
  gallery,
  comment,
  hero,
  links,
  screens,
}) {
  const [loader, setLoader] = useState(false);
  useEffect(() => {
    setTimeout(() => {
      setLoader(true);
    }, 5000);
  });
  console.log(posts[0]);
  console.log(hero);
  console.log(links);

  console.log(gallery[0]);
  // console.log(gallery[0].fields.pics[1].fields);
  const gal = gallery[0].images.map((item, index) => {
    const gallery = [];

    if (index === 0) {
      return { src: item.url, id: item.id, width: 4, height: 3 };
    } else if (index === 1) {
      return { src: item.url, id: item.id, width: 1, height: 1 };
    } else if (index > 1) {
      return { src: item.url, id: item.id, width: 3, height: 4 };
    }
    return item.fields.file.url;
  });

  console.log(gal);

  return loader ? (
    <>
      <div className="">
        <Head>
          <title>GO Food</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header />
        <Hero links={links[0]} text={hero[0]} />
        <Feature props={posts[0].steps} image={posts[0].image.url} />
        <About gallery={gal} text={posts[0].about.text} />
        <Reviews comment={comment} />

        {/*  <Screenshots screen={screens} /> */}
        <Contact />
        <Footer />
      </div>
    </>
  ) : (
    <Loader />
  );
}

export async function getStaticProps() {
  const posts = (await getPosts()) || [];
  const gallery = (await getrecentPosts()) || [];
  const links = (await getLinks()) || [];
  const screens = (await getScreenshot()) || [];
  const comment = (await getComments()) || [];
  const hero = (await getHero()) || [];

  return {
    props: { posts, gallery, links, screens, comment, hero },
  };
}
