import Head from "next/head";
import Image from "next/image";
import { About, Feature, Header, Reviews, Screenshots } from "../components";
import Contact from "../components/Contact";
import Footer from "../components/Footer";
import Hero from "../components/Hero";
import styles from "../styles/Home.module.css";
import getBlogPosts, { getGallery } from "../servicees";

export default function Home({ gallery }) {
  console.log(gallery[0].fields.pics);
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Hero />
      <About />
      <Feature />
      <Screenshots />
      <Reviews />
      <Contact />
      <Footer />
    </div>
  );
}

Home.getInitialProps = async () => {
  const gallery = await getGallery();

  return { gallery };
};
