import Head from "next/head";
import Image from "next/image";
import { About, Feature, Header, Reviews, Screenshots } from "../components";
import Contact from "../components/Contact";
import Footer from "../components/Footer";
import Hero from "../components/Hero";
import styles from "../styles/Home.module.css";
import getAbout, { getGallery, getSteps } from "../servicees";

export default function Home({ props }) {
  console.log(props);
  // console.log(gallery[0].fields.pics[1].fields);
  // const gal = gallery[0].fields.pics.map((item, index) => {
  //   const gallery = [];

  //   if (index === 0) {
  //     return { src: item.fields.file.url, width: 4, height: 3 };
  //   } else if (index === 1) {
  //     return { src: item.fields.file.url, width: 1, height: 1 };
  //   } else if (index > 1) {
  //     return { src: item.fields.file.url, width: 3, height: 4 };
  //   }
  //   return item.fields.file.url;
  // });
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Hero />
      {/* <About gallery={gal} /> */}
      <Feature />
      <Screenshots />
      <Reviews />
      <Contact />
      <Footer />
    </div>
  );
}

Home.getInitialProps = async () => {
  const gallery = await getGallery();

  return { gallery };
};
